# Generated by Django 3.0.5 on 2020-04-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('ship_street', models.CharField(max_length=50)),
                ('ship_city', models.CharField(max_length=50)),
                ('ship_state', models.CharField(max_length=50)),
                ('ship_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('supplierId', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_site.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('tracking_number', models.CharField(max_length=50)),
                ('customer_rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('bill_street', models.CharField(max_length=50)),
                ('bill_city', models.CharField(max_length=50)),
                ('bill_state', models.CharField(max_length=50)),
                ('bill_country', models.CharField(max_length=50)),
                ('bill_postal_code', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_site.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_site.Product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_site.Supplier')),
            ],
        ),
    ]
