# Generated by Django 3.0.5 on 2020-04-27 14:58

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('ship_street', models.CharField(max_length=50)),
                ('ship_city', models.CharField(max_length=50)),
                ('ship_state', models.CharField(max_length=50)),
                ('ship_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=64)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('units_in_stock', models.IntegerField()),
                ('units_on_order', models.IntegerField()),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce_site.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('bill_street', models.CharField(max_length=50)),
                ('bill_city', models.CharField(max_length=50)),
                ('bill_state', models.CharField(max_length=50)),
                ('bill_country', models.CharField(max_length=50)),
                ('bill_postal_code', models.CharField(max_length=50)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_ordered', models.DateTimeField()),
                ('date_shipped', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce_site.Customer')),
                ('product_id', models.ManyToManyField(to='ecommerce_site.Product')),
                ('ship_via', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce_site.Shipper')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce_site.Employee'),
        ),
    ]
